/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author natthawanwannapokin
 */
public class Enquire extends javax.swing.JFrame {

    /**
     * Creates new form Enqiure
     */
    public Enquire() {
        initComponents();
    
    try {
        // สร้างอินสแตนซ์ของ Dateclass และรับวันที่ปัจจุบัน
        Dateclass dateclass = new Dateclass();
        String currentDate = dateclass.getCurrentDate(); // ใช้ getCurrentDate() หรือ CurrentDate() ตามที่คุณออกแบบ

        // แสดงวันที่ใน JTextField
        jdateinEnquire.setText(currentDate);
    } catch (Exception e) {
        // แสดงข้อผิดพลาด
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEnqiureBooking = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jnameinEnqiure = new javax.swing.JLabel();
        btnShow = new javax.swing.JButton();
        jdateinEnquire = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(220, 237, 255));

        jLabel1.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enquire Booking");

        jTableEnqiureBooking.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        jTableEnqiureBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Class Name", "Date", "Check in", "Check out", "Fee"
            }
        ));
        jScrollPane1.setViewportView(jTableEnqiureBooking);

        jButton1.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jnameinEnqiure.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        jnameinEnqiure.setText("Name");

        btnShow.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        btnShow.setText("Show");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        jdateinEnquire.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        jdateinEnquire.setText("date");

        jLabel2.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        jLabel2.setText("Username :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jnameinEnqiure)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jdateinEnquire))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnShow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jnameinEnqiure)
                    .addComponent(jdateinEnquire))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnShow))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");

        jMenuItem1.setText("Back");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menuuuuu fmain =new Menuuuuu();
        fmain.jnameinMenuuuuu.setText(jnameinEnqiure.getText());
        fmain.setVisible(true);
        this.dispose();//ปิดหน้าต่างเดิม
    }//GEN-LAST:event_jButton1ActionPerformed
    DefaultTableModel model;
    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        // TODO add your handling code here:
        String name = jnameinEnqiure.getText().trim();
        if (name.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Name cannot be empty. Please provide a valid name.");
            return;
        }
        name = name.replaceAll("[\\\\/:*?\"<>|]", ""); // ลบอักขระที่ไม่เหมาะสม
        // รับค่าจาก jdateinBoxingclass และตรวจสอบ
        String dateText = jdateinEnquire.getText().trim();
        if (dateText.isEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Date cannot be empty. Please provide a valid date.");
            return;
        }
        dateText = dateText.replaceAll("[\\\\/:*?\"<>|]", ""); // ลบอักขระที่ไม่เหมาะสม
        // สร้าง path ของโฟลเดอร์
        String folderPath = "/Users/thidapondchuanwiriyachan/Downloads/University/P2/csc250/Project/Customer/" + name;
        File folder = new File(folderPath);
        if (!folder.exists()) 
        {
            folder.mkdirs();  // สร้างโฟลเดอร์ถ้าไม่มีก่อน
        }
        // สร้าง path ของไฟล์
        String filePath = folderPath + "/" + dateText + ".txt";
        File file = new File(filePath);
        try 
        {    
            // ตรวจสอบไฟล์
            //File file = new File(filePath);
            if (!file.exists() || file.length() == 0) 
            {
                JOptionPane.showMessageDialog(null, "File does not exist or is empty: " + filePath);
                return;
            }
            // อ่านข้อมูลจากไฟล์
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            // ดึง Model ของ JTable
            DefaultTableModel model = (DefaultTableModel) jTableEnqiureBooking.getModel();
            // ล้างข้อมูลในตารางก่อน เพื่อป้องกันข้อมูลซ้ำ
            model.setRowCount(0);
            // อ่านข้อมูลจากไฟล์ทีละบรรทัด
            String line;
            while ((line = br.readLine()) != null) 
            {
                // สมมติว่าข้อมูลในไฟล์แยกด้วยช่องว่าง (หรือปรับเปลี่ยนตามรูปแบบไฟล์)
                String[] rowData = line.split(" ");
                model.addRow(rowData); // เพิ่มข้อมูลลงใน JTable
            }
            br.close(); // ปิด BufferedReader
        //JOptionPane.showMessageDialog(null, "Data successfully loaded from the file.");
        } 
        catch (Exception e) 
        {
            // จัดการข้อผิดพลาด
            JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnShowActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Menuuuuu fmain = new Menuuuuu(); // เปิดหน้าLogin
        fmain.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enquire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enquire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enquire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enquire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Enquire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShow;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableEnqiureBooking;
    private javax.swing.JLabel jdateinEnquire;
    public javax.swing.JLabel jnameinEnqiure;
    // End of variables declaration//GEN-END:variables
}
