/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thidapondchuanwiriyachan
 */
public class Menuuuuu extends javax.swing.JFrame {
    public Menuuuuu() 
    {
        initComponents();
        try 
        {
        // สร้างอินสแตนซ์ของ Dateclass และรับวันที่ปัจจุบัน
        Dateclass dateclass = new Dateclass();
        String currentDate = dateclass.getCurrentDate(); // ใช้ getCurrentDate() หรือ CurrentDate() ตามที่คุณออกแบบ
        // แสดงวันที่ใน JTextField
        jdateinMenuuuuu.setText(currentDate);
        } 
        catch (Exception e) 
        {
             // แสดงข้อผิดพลาด
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jnameinMenuuuuu = new javax.swing.JLabel();
        jdateinMenuuuuu = new javax.swing.JLabel();
        btnBooking = new javax.swing.JButton();
        btnEnqiureBooking = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnInvoice = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(220, 237, 255));

        jnameinMenuuuuu.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        jnameinMenuuuuu.setText("name");

        jdateinMenuuuuu.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        jdateinMenuuuuu.setText("date");

        btnBooking.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        btnBooking.setText("Booking");
        btnBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingActionPerformed(evt);
            }
        });

        btnEnqiureBooking.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        btnEnqiureBooking.setText("Enqiure Booking");
        btnEnqiureBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnqiureBookingActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu");

        btnInvoice.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        btnInvoice.setText("Invoice");
        btnInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvoiceActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        jLabel2.setText("Username :");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/booking_5486300.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/yesterday_7248642 (1).png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/invoice_12266888.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jnameinMenuuuuu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jdateinMenuuuuu))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBooking)
                                .addGap(18, 18, 18)
                                .addComponent(btnEnqiureBooking))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel3)
                                .addGap(67, 67, 67)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnInvoice)
                            .addComponent(jLabel5))
                        .addGap(0, 41, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdateinMenuuuuu)
                    .addComponent(jLabel2)
                    .addComponent(jnameinMenuuuuu))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnqiureBooking)
                    .addComponent(btnBooking)
                    .addComponent(btnInvoice))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");

        jMenuItem2.setText("Back");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingActionPerformed
        // TODO add your handling code here:
        Booking fmain = new Booking();
        fmain.jnameinBooking.setText(jnameinMenuuuuu.getText());
        fmain.setVisible(true);
        String name = jnameinMenuuuuu.getText();
        try {
                // ตรวจสอบค่า name
                if (name == null || name.trim().isEmpty()) 
                {
                    JOptionPane.showMessageDialog(null, "Name cannot be empty. Please provide a valid name.");
                    return;
                }
                
                name = name.replaceAll("[\\\\/:*?\"<>|]", ""); // ลบอักขระที่ไม่เหมาะสม
                // ตรวจสอบค่า txtDate
                String dateText = jdateinMenuuuuu.getText().trim();
                if (dateText.isEmpty()) 
                {
                    JOptionPane.showMessageDialog(null, "Date cannot be empty. Please provide a valid date.");
                    return;
                }
                dateText = dateText.replaceAll("[\\\\/:*?\"<>|]", ""); // ลบอักขระที่ไม่เหมาะสม  
            
                // ประกาศค่าและสร้่าง folderPath
                String folderPath = "/Users/thidapondchuanwiriyachan/Downloads/University/P2/csc250/Project/Customer/" + name;
                File folder = new File(folderPath);
                // ตรวจว่ามีโฟลเดอร์ไหม ถ้าไม่มีให้สร้าง
                if (!folder.exists()) 
                {
                    folder.mkdirs(); // สร้างโฟลเดอร์ทั้งหมดใน path
                }
                // ประกาศค่าและสร้่างfilePath
                String filePath = folderPath + "/" + dateText + ".txt";
                File file = new File(filePath);
                // ตรวจสอบว่ามีไฟล์อยู่แล้วหรือไม่
                if (file.exists()){} 
                else 
                {
                // เขียนไฟล์ใหม่
                    FileWriter myWriter = new FileWriter(file);
                    myWriter.write(""); // เพิ่มเนื้อหาที่ต้องการเขียน
                    myWriter.close();
                
                }
            } catch (IOException ex) {}
        this.dispose();
    }//GEN-LAST:event_btnBookingActionPerformed

    private void btnEnqiureBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnqiureBookingActionPerformed
        // TODO add your handling code here:
        Enquire fmain = new Enquire();
        fmain.jnameinEnqiure.setText(jnameinMenuuuuu.getText());
        fmain.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEnqiureBookingActionPerformed

    private void btnInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoiceActionPerformed
        // TODO add your handling code here:
        String dateTextt = jdateinMenuuuuu.getText().trim();
        String name = jnameinMenuuuuu.getText().trim();
        if (name.isEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Name cannot be empty. Please provide a valid name.");
            return;
        }
        name = name.replaceAll("[\\\\/:*?\"<>|]", ""); // ลบอักขระที่ไม่เหมาะสม

        // รับค่าจาก jdateinBoxingclass และตรวจสอบ
   
        String dateText = jdateinMenuuuuu.getText().trim();
        if (dateText.isEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Date cannot be empty. Please provide a valid date.");
            return;
        }
        dateText = dateText.replaceAll("[\\\\/:*?\"<>|]", ""); // ลบอักขระที่ไม่เหมาะสม

        // สร้าง path ของโฟลเดอร์
        String folderPath = "/Users/thidapondchuanwiriyachan/Downloads/University/P2/csc250/Project/Customer/" + name;
        File folder = new File(folderPath);
        if (!folder.exists()) 
        {
            folder.mkdirs();  // สร้างโฟลเดอร์ถ้าไม่มีก่อน
        }

        // สร้าง path ของไฟล์
        String filePath = folderPath + "/" + dateText + ".txt";
        File file = new File(filePath);
  
        
        try 
        {
            // ตรวจสอบไฟล์
            if (!file.exists() || file.length() == 0) 
            {
                JOptionPane.showMessageDialog(null, "File does not exist or is empty: " + filePath);
                return;
            }

            // อ่านข้อมูลจากไฟล์
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);

            double total = 0.0; // ตัวแปรสำหรับเก็บผลรวม
            String line;

            while ((line = br.readLine()) != null) 
            {
               // แยกข้อมูลในบรรทัดด้วยตัวคั่น เช่น ช่องว่าง
               String[] parts = line.split(" ");
               if (parts.length > 4) 
               { // ตรวจสอบว่ามีข้อมูลใน index 4 หรือไม่
                   try 
                   {
                       double value = Double.parseDouble(parts[4].trim()); // แปลงเป็น double
                       total += value; // เพิ่มลงในผลรวม
                    } 
                    catch (NumberFormatException e) 
                    {
                        System.out.println("Skipping invalid number format: " + parts[5].trim());
                    }
                }
            }

            br.close(); // ปิด BufferedReader

             // แสดงผลรวม
            JOptionPane.showMessageDialog(null, "Date : "+ dateTextt +"\n"+"Username : " + name + "\n" + "Fee : " + total+"\n"+"Thank you" );
            Menuuuuu fmain = new Menuuuuu();
            fmain.setVisible(true);     
        } 
        catch (Exception e) 
        {
            // จัดการข้อผิดพลาด
            JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage());
            e.printStackTrace();
        }
        this.dispose();
    }//GEN-LAST:event_btnInvoiceActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Loginnnnn fmain = new Loginnnnn(); // เปิดหน้าLogin
        fmain.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menuuuuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menuuuuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menuuuuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menuuuuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menuuuuu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBooking;
    private javax.swing.JButton btnEnqiureBooking;
    private javax.swing.JButton btnInvoice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jdateinMenuuuuu;
    public javax.swing.JLabel jnameinMenuuuuu;
    // End of variables declaration//GEN-END:variables
}
